### ISSUE TITLE
toLowerCase in eventListener

### ISSUE THREAD

**Issue by jschaeke** [nicojanssens/qbus-eqoweb-api#1]
I am using your library to bridge qbus to mqtt (https://github.com/jschaeke/qbusMqtt2), I noticed this lowercase causing some inconsistencies; but worked around it. Is there any reason it was added here?
https://github.com/nicojanssens/qbus-eqoweb-api/blob/c66358bb06f7e4ecc41f645431a3f6ccad55f0c5/lib/EventListener.js#L71

**Comment by nicojanssens** [comment]
I added this to handle inconsistent casing in my qbus config. Will remove it in the next patch release.

**Comment by nicojanssens** [comment]
done -- @jschaeke could you have a look?

**Comment by jschaeke** [comment]
@nicojanssens will do, any chance the timeout can be added too (issue 2)?

**Comment by nicojanssens** [comment]
Sure, np. Will have a look at the beginning of next week.
