### ISSUE TITLE
timeout missing?

### ISSUE THREAD

**Issue by jschaeke** [nicojanssens/qbus-eqoweb-api#2]
As the eventlistener at unpredicted times just halt without errors I suspect a timeout might be missing?
https://github.com/nicojanssens/qbus-eqoweb-api/blob/c66358bb06f7e4ecc41f645431a3f6ccad55f0c5/lib/Connect.js#L24

https://github.com/axios/axios/blob/master/lib/defaults.js#L71

At this moment haven't tried it out yet..

**Comment by nicojanssens** [comment]
@jschaeke I added a timeout to the axios requests and made it configurable via env variables. You should now get an error if your qbus controller is unreachable.

Note that in the current implementation the EventListeren will still halt if it cannot reach the controller.

Can you test this out? I've been using this lib for quite some time, and didn't face unexpected failures so far.

**Comment by jschaeke** [comment]
@nicojanssens I just rebuild and updated the container; it's running on a small vps (scaleway arm64) to a remote eqoweb over vpn, so network might be prone to errors. We'll evaluate it for a while and do the necessary adjustments to get it reliable if necessary.

**Comment by nicojanssens** [comment]
Perfect. Will close this issue for now. Let me know if you’d be facing other issues.

**Comment by jschaeke** [comment]
Didn't take too long to see it work:
https://gist.github.com/jschaeke/1d7fa9197e0b60a3583d6d8820219e51

**Comment by jschaeke** [comment]
Update: although it looked like it recovered after timeout, ultimately it still stalled for no apparent reason. We've moved the app (https://github.com/jschaeke/qbusMqtt2) from a remote vps over vpn to a raspberry pi within the local network and since then it is running flawlessly.
